INSERT INTO month (id, name, number) VALUES (DEFAULT, 'jaanuar', 1);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'veebruar', 2);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'märts', 3);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'aprill', 4);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'mai', 5);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'juuni', 6);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'juuli', 7);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'august', 8);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'september', 9);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'oktoober', 10);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'november', 11);
INSERT INTO month (id, name, number) VALUES (DEFAULT, 'detsember', 12);

INSERT INTO role (id, name) VALUES (DEFAULT, 'admin');
INSERT INTO role (id, name) VALUES (DEFAULT, 'customer');

INSERT INTO "user" (id, role_id, user_name, password, email) VALUES (DEFAULT, 2, 'liisi', 'student123', 'liisi@budgebuddy.com');
INSERT INTO "user" (id,  role_id, user_name, password, email) VALUES (DEFAULT, 2, 'maris', 'student123', 'maris@budgetbuddy.com');
INSERT INTO "user" (id,  role_id, user_name, password, email) VALUES (DEFAULT, 2, 'katri', 'student123', 'katri@budgetbuddy.com');

INSERT INTO standard_category (id, name, sequence, type) VALUES (DEFAULT, 'Aktiivsed tulud', 1, 'i');
INSERT INTO standard_category (id, name, sequence, type) VALUES (DEFAULT, 'Passiivsed tulud', 2, 'i');
INSERT INTO standard_category (id, name, sequence, type) VALUES (DEFAULT, 'Vältimatud kulud', 3, 'e');
INSERT INTO standard_category (id, name, sequence, type) VALUES (DEFAULT, 'Eluase', 4, 'e');
INSERT INTO standard_category (id, name, sequence, type) VALUES (DEFAULT, 'Hooajalised kulud', 5, 'e');
INSERT INTO standard_category (id, name, sequence, type) VALUES (DEFAULT, 'Elukvaliteet', 6, 'e');
INSERT INTO standard_category (id, name, sequence, type) VALUES (DEFAULT, 'Lapsed', 7, 'e');
INSERT INTO standard_category (id, name, sequence, type) VALUES (DEFAULT, 'Meelelahutus', 8, 'e');

INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Palk', 1, 'i');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Lastetoetus', 2, 'i');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Muu aktiivne tulu', 3, 'i');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Dividendid', 4, 'i');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Üüritulu', 5, 'i');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Intressid', 6, 'i');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Muu passiivne tulu', 7, 'i');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Toidupood', 8, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Transport', 9, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Lemmikloom', 10, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Telefon', 11, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kodukulud', 12, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Ravikulud', 13, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Tasud ja viivised', 14, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Laenumakse / üür', 15, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Elekter', 16, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kommunaalid', 17, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Internet / televiisor', 18, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kindlustus', 19, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Riided', 20, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kingitused', 21, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Annetused', 22, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kodutehnika', 23, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Aed', 24, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Puhkus', 25, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Mugavusteenused', 26, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Trenn', 27, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Ilukulud', 28, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Trennid / hobid', 29, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Riided', 30, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Laste meelelahutus', 31, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Väljas söömine', 32, 'e');
INSERT INTO standard_subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Meelelahutus', 33, 'e');


INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 1, 1);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 1, 2);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 1, 3);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 2, 4);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 2, 5);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 2, 6);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 2, 7);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 3, 8);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 3, 9);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 3, 10);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 3, 11);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 3, 12);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 3, 13);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 3, 14);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 4, 15);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 4, 16);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 4, 17);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 4, 18);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 4, 19);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 5, 20);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 5, 21);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 5, 22);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 5, 23);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 5, 24);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 6, 25);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 6, 26);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 6, 27);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 6, 28);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 7, 29);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 7, 30);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 7, 31);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 8, 32);
INSERT INTO standard_category_relation (id, standard_category_id, standard_subcategory_id) VALUES (DEFAULT, 8, 33);

INSERT INTO account_type (id, name, description) VALUES (DEFAULT, 'Arvelduskonto', 'Tavaline arvelduskonto, kust teed igapäevaseid makseid');
INSERT INTO account_type (id, name, description) VALUES (DEFAULT, 'Säästukonto / hoius', 'Arvelduskonto, kuhu paned raha kõrvale');
INSERT INTO account_type (id, name, description) VALUES (DEFAULT, 'Krediitkaart', 'See kaart, mis võib miinusesse minna');
INSERT INTO account_type (id, name, description) VALUES (DEFAULT, 'Investeerimiskonto', 'Pangakonto, millelt teed investeeringuid');
INSERT INTO account_type (id, name, description) VALUES (DEFAULT, 'Kodulaen', 'Kodulaenu jääk');
INSERT INTO account_type (id, name, description) VALUES (DEFAULT, 'Muu laen', 'Muu laenu jääk');

INSERT INTO account (id, user_id, account_type_id, name, description, balance) VALUES (DEFAULT, 1, 1, 'Konto LHV pangas', 'Minu konto LHV pangas', 100);
INSERT INTO account (id, user_id, account_type_id, name, description, balance) VALUES (DEFAULT, 1, 3, 'Swedbank krediitkaart', 'Kredekas', 0);
INSERT INTO account (id, user_id, account_type_id, name, description, balance) VALUES (DEFAULT, 1, 2, 'SEB konto', 'SEB säästukonto', 2500);

INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 1, 'Aktiivsed tulud', 1, 'i');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 1, 'Passiivsed tulud', 2, 'i');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 1, 'Vältimatud kulud', 3, 'e');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 1, 'Eluase', 4, 'e');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 1, 'Hooajalised kulud', 5, 'e');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 1, 'Elukvaliteet', 6, 'e');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 1, 'Lapsed', 7, 'e');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 1, 'Meelelahutus', 8, 'e');

INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Palk', 1, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Lastetoetus', 2, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Muu aktiivne tulu', 3, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Dividendid', 4, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Üüritulu', 5, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Intressid', 6, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Muu passiivne tulu', 7, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Toidupood', 8, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Transport', 9, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Lemmikloom', 10, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Telefon', 11, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kodukulud', 12, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Ravikulud', 13, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Tasud ja viivised', 14, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Laenumakse / üür', 15, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Elekter', 16, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kommunaalid', 17, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Internet / televiisor', 18, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kindlustus', 19, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Riided', 20, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kingitused', 21, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Annetused', 22, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kodutehnika', 23, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Aed', 24, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Puhkus', 25, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Mugavusteenused', 26, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Trenn', 27, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Ilukulud', 28, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Trennid / hobid', 29, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Riided', 30, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Laste meelelahutus', 31, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Väljas söömine', 32, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Meelelahutus', 33, 'e');

INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 1, 1, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 1, 2, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 1, 3, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 2, 4, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 2, 5, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 2, 6, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 2, 7, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 3, 8, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 3, 9, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 3, 10, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 3, 11, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 3, 12, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 3, 13, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 3, 14, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 4, 15, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 4, 16, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 4, 17, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 4, 18, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 4, 19, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 5, 20, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 5, 21, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 5, 22, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 5, 23, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 5, 24, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 6, 25, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 6, 26, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 6, 27, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 6, 28, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 7, 29, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 7, 30, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 7, 31, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 8, 32, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 8, 33, TRUE);

INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 2, 'Aktiivsed tulud', 1, 'i');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 2, 'Passiivsed tulud', 2, 'i');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 2, 'Vältimatud kulud', 3, 'e');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 2, 'Eluase', 4, 'e');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 2, 'Hooajalised kulud', 5, 'e');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 2, 'Elukvaliteet', 6, 'e');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 2, 'Lapsed', 7, 'e');
INSERT INTO category (id, user_id, name, sequence, type) VALUES (DEFAULT, 2, 'Meelelahutus', 8, 'e');

INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Palk', 1, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Lastetoetus', 2, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Muu aktiivne tulu', 3, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Dividendid', 4, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Üüritulu', 5, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Intressid', 6, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Muu passiivne tulu', 7, 'i');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Toidupood', 8, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Transport', 9, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Lemmikloom', 10, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Telefon', 11, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kodukulud', 12, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Ravikulud', 13, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Tasud ja viivised', 14, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Laenumakse / üür', 15, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Elekter', 16, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kommunaalid', 17, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Internet / televiisor', 18, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kindlustus', 19, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Riided', 20, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kingitused', 21, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Annetused', 22, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Kodutehnika', 23, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Aed', 24, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Puhkus', 25, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Mugavusteenused', 26, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Trenn', 27, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Ilukulud', 28, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Trennid / hobid', 29, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Riided', 30, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Laste meelelahutus', 31, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Väljas söömine', 32, 'e');
INSERT INTO subcategory (id, name, sequence, type) VALUES (DEFAULT, 'Meelelahutus', 33, 'e');

INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 9, 34, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 9, 35, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 9, 36, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 10, 37, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 10, 38, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 10, 39, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 10, 40, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 11, 41, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 11, 42, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 11, 43, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 11, 44, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 11, 45, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 11, 46, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 11, 47, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 12, 48, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 12, 49, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 12, 50, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 12, 51, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 12, 52, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 13, 53, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 13, 54, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 13, 55, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 13, 56, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 13, 57, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 14, 58, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 14, 59, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 14, 60, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 14, 61, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 15, 62, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 15, 63, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 15, 64, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 16, 65, TRUE);
INSERT INTO category_relation (id, category_id, subcategory_id, is_active) VALUES (DEFAULT, 16, 66, TRUE);

INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-08-01',8,'Selver',10.4,'e',true);
INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-08-02',8,'Selver',100.22,'e',true);
INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-08-05',8,'Selver',25.78,'e',true);
INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-08-05',9,'Kulu',25.41,'e',true);
INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-09-01',8,'Selver',10.03,'e',true);
INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-09-02',8,'Rimi',7.55,'e',true);
INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-09-05',8,'Selver toit',45.70,'e',true);

INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-08-10',1,'Augusti Palk',1900,'i',true);
INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-08-10',2,'Augusti lastetoetus',60,'i',true);
INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-08-10',4,'Divikad',20.50,'i',true);
INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-08-10',5,'Üür sisse',220,'i',true);
INSERT INTO transaction (id, user_id,sender_account_id,receiver_account_id,date,subcategory_id,description,amount,type,is_active) VALUES (DEFAULT,1,1,NULL,'2022-08-10',6,'Intress',14,'i',true);

INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 2000, 1, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 60, 2, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 40, 3, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 45, 4, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 250, 5, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 15, 6, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 12, 7, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 400, 8, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 120, 9, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 100,10, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 15, 11, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 60, 12, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 25, 13, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 10, 14, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 500,15, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 45, 16, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 75, 17, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 20, 18, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 15, 19, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 150,20, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 50, 21, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 20, 22, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 30, 23, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 100,24, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 250,25, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 30, 26, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 45, 27, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 50, 28, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 60, 29, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 50, 30, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 30, 31, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 50, 32, true);
INSERT INTO budgeted (id, user_id, year, month_id, amount, subcategory_id, is_active) VALUES (DEFAULT, 1, 2022, 8, 50, 33, true);